testing

diff --git a/.github/workflows/publish-charts.yml b/.github/workflows/publish-charts.yml
--- a/.github/workflows/publish-charts.yml
+++ b/.github/workflows/publish-charts.yml
@@ -16,7 +16,26 @@ jobs:
         uses: actions/checkout@v6
         with:
           fetch-depth: 0
-
+      - name: Pre-release checks
+        run: |
+            for chart in charts/*; do
+              [ -f "$chart/Chart.yaml" ] || continue
+              NAME=$(yq '.name' "$chart/Chart.yaml")
+              VERSION=$(yq '.version' "$chart/Chart.yaml")
+              APP_VERSION=$(yq '.appVersion // "N/A"' "$chart/Chart.yaml")
+              echo "Chart: $NAME, Version: $VERSION, App Version: $APP_VERSION"
+              if [[ "$APP_VERSION" != "$GITHUB_REF_NAME" ]]; then
+                echo "Error: Chart App version $APP_VERSION does not match tag $GITHUB_REF_NAME"
+                echo "Please update the appVersion field in $chart/Chart.yaml to match the tag version before releasing."
+                exit_code=1
+              fi
+              if [[ "$VERSION" != "$GITHUB_REF_NAME" ]]; then
+                echo "Error: Chart version $VERSION does not match tag $GITHUB_REF_NAME"
+                echo "Please update the version field in $chart/Chart.yaml to match the tag version before releasing."
+                exit_code=1
+              fi
+            done
+            exit ${exit_code:-0}
       - name: Package helm charts
         run: |
           mkdir packages
